version: ''.
services:
    app:
        image: juscelinoribeiro/crud
        container_name: app
        ports:
          - 8080:80
	link:     
          - mysql
	depends_on:
          - mysql

    db:
    image: mysql
    container_name: db
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
